---
title: "Example 2: Overdispersion"
author: "David Hodgson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example 2: Overdispersion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Load the packages

```{r}

#install.packages("devtools")
#library(devtools)
devtools::load_all()
library(lubridate)
library(patchwork)
library(tidybayes)
library(ggdist)
library("invgamma")

# https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017

# Geneerate data

data_full <- read.csv(here::here("data", "results.csv"))
score_2024 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) 

````


```{r}


# hyper-parameters for the gamma distribution of lambda
alpha_l <- 25
beta_l <- 10 
# gives mean of 2.5

# hyper-parameters for the inv-gamma distribution of r
alpha_r <- 1
beta_r <- 10
# these priors give an average of 25% extra variance for the negative binomial distribution

mu <- var(score_2024$total ) / mean(score_2024$total )
sigma <- 1

model <- list(

  lowerParSupport_fitted = c(-8),
  upperParSupport_fitted = c(8),

  namesOfParameters = c("sigma"),

  sampleInitPrior = function(datalist) {
   # cat("sampleInitPrior", "\n")

    rnorm(1, 0, 1)
  },

  sampleInitJump = function(params, datalist) {
   # cat("sampleInitJump", "\n")
    lambda <- rgamma(1, alpha_l,  beta_l) # sample lambda
    r <- rgamma(1, alpha_r, beta_r) # sample r

    as.matrix(c(1, lambda, r), nrow = 1)
  },

  evaluateLogPrior = function(params, jump, datalist) {
    #cat("evaluateLogPrior", "\n")
   

    p <- log(0.5)

    p <- p + log(dgamma(jump[2], alpha_l,  beta_l))

    if (jump[1] == 2) {
      p <- p + log(dgamma(jump[3], alpha_r, beta_r))
    }


    p
  },

  evaluateLogLikelihood = function(params, jump, datalist) {
    #cat("evaluateLogLikelihood", "\n")
    ll <- 0

    z <- datalist$obs
    N_data <- datalist$N_data

    if (jump[1] == 1) {
      lambda <- jump[2]
      # log likelihood of the poisson distribution
      for (i in 1:N_data) {
          ll <- ll - lambda + z[i] * log(lambda) - lfactorial(z[i])
      }
    } else {
      lambda <- jump[2]
      r <- jump[3]

      # log likelihood of the negative binomial distribution
      for (i in 1:N_data) {
        ll <- ll + z[i]*log(lambda) - lfactorial(z[i]) + lgamma(1/r + z[i]) -
           lgamma(1/r) - z[i]*log(1/r + lambda) - 1/r * log(1 + r*lambda)
        #ll <- ll - log(r + z[i]) - lfactorial(z[i]) - lgamma(r) + r * log(r / (r + lambda)) + z[i] * log(lambda / (lambda + r))
      }
    }
    ll
  },

  sampleBirthProposal =  function(params, jump, i_idx, datalist) {
    #cat("sampleBirthProposal", "\n")
    u <- rnorm(1, 0, sigma)
    r <- mu * exp(u)
    jump[3] <- r
    jump[1] <- 2
    jump
  },

  sampleDeathProposal = function(params, jump, i_idx, datalist) {
    #cat("sampleDeathProposal", "\n")

    # going from negative binomial to poisson
    # no random variable required but note that linear transformation is u = log(r / mu)
    jump[1] <- 1
    jump
  },

  evaluateBirthProposal = function(params, jump, i_idx, datalist) {
  #  cat("evaluateBirthProposal: ")
    r <- jump[3]
    u <- log(r / mu)
    #cat(log(1 / dnorm(u, 0, sigma)) + log(mu * exp(u)), "\n")

    log(1 / dnorm(u, 0, sigma)) + log(r)
  },

  evaluateDeathProposal = function(params, jump, i_idx, datalist) {
    #cat("evaluateDeathProposal: ")

    r <- jump[3]
    u <- log(r / mu)
   # cat(log(dnorm(u, 0, sigma)) + log(1 / (r)), "\n")

    log(dnorm(u, 0, sigma)) + log(1 / r)
  },

  sampleJump = function(params, jump, i_idx, datalist) {

    N <- ncol(jump)

    lambda_new <- max(jump[2] + rnorm(1, 0, 0.2), 0.0000)
    if (jump[1] == 2) {
      r_new <-  max(jump[3] + rnorm(1, 0, 0.02), 0.0000)
    } else {
      r_new <- jump[3] 
    }

    jump[2] <- lambda_new
    jump[3] <- r_new

    jump
  },

  sampleProposal = function(params, jump, datalist) {
    q <- c(0.33, 0.67, 1.0)
    q
  }

)

```

# Define settings and run the model, (this won't run as made the data up)

```{r eval = FALSE}

devtools::load_all()

settings <-  list(
    numberChainRuns = 4,
    numberCores = 4,
    iterations = 4000,
    burninPosterior = 2000,
    thin = 10,
    runParallel = FALSE,
    onDebug = FALSE
)

# Run the model 

score_1900 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("1900-01-01"))

score_1920 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("1920-01-01") & date > ymd("1900-01-01"))

score_1940 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("1940-01-01") & date > ymd("1920-01-01"))

score_1960 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("1960-01-01") & date > ymd("1940-01-01"))

score_1980 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("1980-01-01") & date > ymd("1960-01-01"))

score_2000 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("2000-01-01") & date > ymd("1980-01-01"))

score_2020 <- data_full %>% mutate(id = 1:nrow(.), date = ymd(date), total = home_score + away_score) %>%
  select(id, date, total) %>% filter(date < ymd("2020-01-01") & date > ymd("2019-01-01"))

data_name <- c("1900", "1920", "1940", "1960", "1980", "2000", "2020")
data_all <- list(score_1900, score_1920, score_1940, score_1960, score_1980, score_2000, score_2020)


data_name <- c("2020")
data_all <- list(score_2020)
j <- 1
for (i in data_name) {
  obs <- data_all[[j]]$total
  data_l <- list(
      obs = obs,
      N_data = length(obs)
  )

  outputs <- rjmc_func(model, data_l, settings)
  saveRDS(outputs, here::here("outputs", "fits", "overdisp", paste0("fit_sim_", i, ".RDS")))
  j <- j + 1

}

```

# Plot outputs 

```{r}


j <- 3

data_name <- c("1900", "1920", "1940", "1960", "1980", "2000", "2020")
data_all <- list(score_1900, score_1920, score_1940, score_1960, score_1980, score_2000, score_2020)

obs <- data_all[[j]]$total
data_l <- list(
    obs = obs,
    N_data = length(obs)
)

outputs <- readRDS(here::here("outputs", "fits", "overdisp", paste0("fit_sim_", data_name[j], ".RDS")))


G <- names(data.frame(data_l$obs) %>% table) %>% as.numeric %>% max
sum <-  (data.frame(data_l$obs) %>% table) / sum((data.frame(data_l$obs) %>% table) )
data_col <- data.frame(
  s = as.numeric(names(sum)),
  values = as.numeric(sum)
)

require(patchwork)

n_chain <- 4
outputs$jump[[1]]

tables_length <- get_lengths(n_chain)

mode_post <- names(sort(tables_length, decreasing = TRUE))[1]
mix_size <- mode_post

s <<- 1
summary_post <- map_df(1:n_chain,
  function(c) {
    list_outputs_mode <- list()
    j <- 1
    for (i in 1:length(outputs$jump[[c]])) {
        if ((outputs$jump[[c]][[i]] %>% ncol) == mix_size) {
            sample_i <- (outputs$jump[[c]][[i]])
            list_outputs_mode[[j]] <- data.frame(
                k = sample_i[1],
                lambda = sample_i[2],
                r = sample_i[3],
                sample = s,
                chain = c
            )
            s <<- s + 1
            j <- j + 1
        }
    }
    list_outputs_mode %>% bind_rows()
  }
)


summary_post_pars <- summary_post %>% select(k, lambda, r) %>%
   mutate(p = 1 / (lambda * r + 1), n = 1 / r) 

summary_post_pars_pois <- summary_post_pars %>% filter(k == 1) %>% select(lambda)
summary_post_pars_neg <- summary_post_pars %>% filter(k == 2) %>% select(p, n)

post_poi <- map_df(1:nrow(summary_post_pars_pois), 
  ~data.frame(
    s = 0:G,
    value = dpois(0:G, summary_post_pars_pois[.x, ])
  )
) %>% group_by(s) %>% mean_qi

post_negbion <- map_df(1:nrow(summary_post_pars_neg), 
  ~data.frame(
    s = 0:G,
    value = dnbinom(0:G,  summary_post_pars_neg[.x, 2], summary_post_pars_neg[.x, 1])
  )
) %>% group_by(s) %>% mean_qi


p1 <- ggplot() + 
  geom_col(data = data_col, aes(x = s, y = values), fill = "gray" ) + 
  geom_ribbon(data = post_poi, aes(x = s, ymin = .lower, ymax = .upper), fill = "red", alpha = 0.5) + 
  geom_line(data = post_poi, aes(x = s, y = value), color = "red") +
  geom_ribbon(data = post_negbion, aes(x = s, ymin = .lower, ymax = .upper), fill = "blue", alpha = 0.5) + 
  geom_line(data = post_negbion, aes(x = s, y = value), color = "blue") +
  theme_bw() + labs(x = "Goals per match", y = "Density")

p2 <- data.frame(
  model = c("Poission", "Negative Binomial"),
  prop = as.numeric((summary_post$k %>% table) / sum(summary_post$k %>% table))
) %>% 
  ggplot() + 
    geom_col(aes(y = model, x = prop, fill = model)) + 
    scale_fill_manual(values = c("blue", "red")) +
  theme_bw() + labs(x = "Prop of posterior", y = "", fill = "Model")

p1 / p2 + plot_layout(guides = "collect", heights = c(2, 1)) + 
  plot_annotation(title = "Goals scored in international football matches prior to 1900")



```


